# Generated by Django 5.2.7 on 2025-12-22 05:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='tran_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(default='category.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='product.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default=10, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default=0.5, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=cloudinary.models.CloudinaryField(default='vendor.jpg', max_length=255, verbose_name='image'),
        ),
    ]
